apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"niko-jira:latest","namespace":"jira"},"fieldPath":"spec.template.spec.containers[?(@.name==\"niko-jira\")].image"}]'
    generation: 2
    labels:
      app: niko-jira
      app.kubernetes.io/component: niko-jira
      app.kubernetes.io/instance: niko-jira
    name: niko-jira
    namespace: jira
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: niko-jira
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          deployment: niko-jira
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/jira/niko-jira:latest
          imagePullPolicy: IfNotPresent
          name: niko-jira
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
#        securityContext:
#          runAsUser: 1000
        terminationGracePeriodSeconds: 30
kind: List
